Adding Loader Activities
FunnelEnvy/activities-loader pull request #21
Opened 2023-09-12 21:51 UTC by connortobrien

2023-09-12 22:10 UTC, connortobrien commented on load-activities.js
> +			// 	return false; //Activity is to be OFF for MTP7
@wilsonweb is this code used (I commented it out)

2023-09-19 16:52 UTC, wilsonweb requested changes
I am marking this **Request changes**, though maybe it is more of just something to talk about.

I see how you have functions to do things w/i activity loader that are globally accessible, like: 
```
           window.${process.env.REUSABLE_FN}.getActivities = getActivities;
			window.${process.env.REUSABLE_FN}.getSites = getSites;
			window.${process.env.REUSABLE_FN}.setSites = setSites;
			window.${process.env.REUSABLE_FN}.detectTypeOfSite = detectTypeOfSite;
``` 

These methods become accessable globally via the global lib, and that is fine.
I am thinking that such browser global functions would not have access to `let activities = [];` from `load-activities.js`
I had figured you'd create a new lib, something like `window.FeActivityLoader` that would house all of that.

- The way the code is in this pull #21 should work for our current code and needs
- I would expect ` window.${process.env.REUSABLE_FN}.getActivities` would not work, 
- - and that is fine, we can use global var `FE_LOADER_v2` for debugging
- calls like this would likely fail `window['feHPEB2C'].getSelectorsDictionaryById(ProjectData.FeProjectId)` 
- - this is only used in 8 activities (fallbacks are inplace), grep `activities.json` for `SelectorsDictionary`
- - this was part of our plan to be able to manage activity selectors via `activities.json` (and maybe Retool)
- - - we had hoped to make it easier to adapt to site changes w/o having to touch the code     
- - - plan has sort of fell to be outside of our attention span lately.          
- - - ? is the activities.json available in the browser somehow? if so we can handle it a different way

2023-09-20 19:03 UTC, wilsonweb commented
looks good

2023-09-20 19:05 UTC, wilsonweb approved these changes

2023-09-20 22:09 UTC, merged